version: '3.4'
services:
  vue-enterprise-boilderplate:
    build:
      context: ../
      target: dev-stage
    volumes:
      - ../:/home/app
      - $HOME/.ssh:/home/node/.ssh
      # For permanat install extension
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vscode-extension-volume-vue-enterprise-boilderplate:/home/node/.vscode-server/extensions
      - vscode-extension-volume-insiders-vue-enterprise-boilderplate:/home/node/.vscode-server-insiders/extensions
    working_dir: /home/app/
    command: tail -f /dev/null
    user: node
    ports:
      - 5858:5858
      - 8080:8080
    environment:
      - NODE_ENV=development
    networks:
      default:
    tty: true
volumes:
  vscode-extension-volume-vue-enterprise-boilderplate:
  vscode-extension-volume-insiders-vue-enterprise-boilderplate:
