version: '3.4'
services:
  vue-enterprise-boilderplate:
    build:
      context: ../
      target: release-stage
    volumes:
      # - ../:/home/app
      - $HOME/.ssh:/home/nginx/.ssh
    working_dir: /home/app/
    restart: on-failure
    command: [nginx-debug, '-g', 'daemon off;']
    user: nginx
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production
    networks:
      default:
    tty: true
