/**
 * @readonly
 * @enum {string}
 */
export const DbError = {
  ID_INVALID: 'ID_INVALID',
  FIELD_IS_REQUIRED: 'FIELD_IS_REQUIRED',
  FIELD_LENGTH_MAX: 'FIELD_LENGTH_MAX',
  FIELD_IS_UNIQUE: 'FIELD_IS_UNIQUE',
  POSITIVE_NUMBER_ONLY: 'POSITIVE_NUMBER_ONLY',
  EMAIL_ALREADY_CONFIRMED: 'EMAIL_ALREADY_CONFIRMED',
  ACCOUNT_ALREADY_EXIST: 'ACCOUNT_ALREADY_EXIST',
  EMAIL_ALREADY_EXIST: 'EMAIL_ALREADY_EXIST',
  PHONE_ALREADY_EXIST: 'PHONE_ALREADY_EXIST',
  PHONE_PREFIX_EXIST: 'PHONE_PREFIX_EXIST',
  PHONE_PREFIX_NOT_EXIST: 'PHONE_PREFIX_NOT_EXIST',
  INVALID_CONFIRMATION_CODE_LENGTH: 'INVALID_CONFIRMATION_CODE_LENGTH',
  ACCOUNT_ALREADY_HAS_POLICY_DOCUMENT: 'ACCOUNT_ALREADY_HAS_POLICY_DOCUMENT',
  ACCOUNT_IS_REQUIRE_IN_POLICY_DOCUMENT:
    'ACCOUNT_IS_REQUIRE_IN_POLICY_DOCUMENT',
  REQUIRE_POLICY_NAME: 'REQUIRE_POLICY_NAME',
  POLICY_NOT_EXIST: 'POLICY_NOT_EXIST',
};

/**
 * @readonly
 * @enum {string}
 */
export const UserError = {
  USER_INPUT_INVALID: 'USER_INPUT_INVALID',
  ACCOUNT_REQUIRED: 'ACCOUNT_REQUIRED',
  AVATAR_MIME_DENIED: 'AVATAR_MIME_DENIED',
  UPLOAD_AVATAR_FAIL: 'UPLOAD_AVATAR_FAIL',
  AVATAR_NOT_FOUND: 'AVATAR_NOT_FOUND',
  INVALID_PERMISSION: 'INVALID_PERMISSION',
  ROLE_SETTING_FAIL: 'ROLE_SETTING_FAIL',
  CONFIRMATION_FAIL: 'CONFIRMATION_FAIL',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  ACCOUNT_ALREADY_VERIFIED: 'ACCOUNT_ALREADY_VERIFIED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_ALREADY_CONNECT: 'ACCOUNT_ALREADY_CONNECT',
  INVALID_TOKEN: 'INVALID_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  INVALID_VERIFY_CODE_COUNTDOWN: 'INVALID_VERIFY_CODE_COUNTDOWN',
  NOT_MATCH_OLD_PASSWORD: 'NOT_MATCH_OLD_PASSWORD',
  NOT_MATCH_PASSWORD: 'NOT_MATCH_PASSWORD',
  NOT_INCLUDE_OLD_PASSWORD: 'NOT_INCLUDE_OLD_PASSWORD',
  INCORRECT_EMAIL_FORMAT: 'INCORRECT_EMAIL_FORMAT',
  INCORRECT_PHONE_FORMAT: 'INCORRECT_PHONE_FORMAT',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  INVALID_RESET_PASSWORD_TOKEN: 'INVALID_RESET_PASSWORD_TOKEN',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_ACCOUNT: 'INVALID_ACCOUNT',
  INVALID_VERIFY_CODE: 'INVALID_VERIFY_CODE',
  CONFIRMATION_PASSWORD_REQUIRED: 'CONFIRMATION_PASSWORD_REQUIRED',
  POLICY_NOT_EXIST: 'POLICY_NOT_EXIST',
  INVALID_POLICY_FORMAT: 'INVALID_POLICY_FORMAT',
  POLICY_BANNED: 'POLICY_BANNED',
  SEARCH_USER_INPUT_MIN_LENGTH: 'SEARCH_USER_INPUT_MIN_LENGTH',
};

/**
 * @readonly
 * @enum {string}
 */
export const CommonError = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  INVALID_IMAGE_FORMAT: 'INVALID_IMAGE_FORMAT',
  INVALID_TIME_FORMAT: 'INVALID_TIME_FORMAT',
  RECAPTCHA_NOT_VALID: 'RECAPTCHA_NOT_VALID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FIELD_IS_REQUIRED: 'FIELD_IS_REQUIRED',
  REQUIRED_AT_LEAST_ONE_FIELD: 'REQUIRED_AT_LEAST_ONE_FIELD',
  INVALID_HEX_COLOR_FORMAT: 'INVALID_HEX_COLOR_FORMAT',
  MUST_LESS_THAN: 'MUST_LESS_THAN',
};

/**
 * @readonly
 * @enum {string}
 */
export const FileManagerError = {
  RANGE_HEADER_NOT_FOUND: 'RANGE_HEADER_NOT_FOUND',
  RANGE_HEADER_NOT_VALID: 'RANGE_HEADER_NOT_VALID',
  UPLOAD_SESSION_NOT_FOUND: 'UPLOAD_SESSION_NOT_FOUND',
  UPLOAD_CHUNK_FAIL: 'UPLOAD_CHUNK_FAIL',
  FILE_SIZE_EXCEED: 'FILE_SIZE_EXCEED',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FOLDER_NAME_REQUIRED: 'FOLDER_NAME_REQUIRED',
  CHUNK_IS_REQUIRED: 'CHUNK_IS_REQUIRED',
  FILE_NAME_REQUIRED: 'FILE_NAME_REQUIRED',
  FILE_SIZE_REQUIRED: 'FILE_SIZE_REQUIRED',
  INVALID_PUBLIC_STATUS: 'INVALID_PUBLIC_STATUS',
  INVALID_FILE_TAG: 'INVALID_FILE_TAG',
  FILE_UPLOAD_OVER_EXCEED: 'FILE_UPLOAD_OVER_EXCEED',
  CREATE_UPLOAD_SESSION_FAIL: 'CREATE_UPLOAD_SESSION_FAIL',
  CANT_UPDATE_ROOT_FOLDER: 'CANT_UPDATE_ROOT_FOLDER',
  INVALID_FOLDER_ICON: 'INVALID_FOLDER_ICON',
  REACH_LIMIT_UPLOAD_SESSION: 'REACH_LIMIT_UPLOAD_SESSION',
  FOLDER_MODIFY_DENIED: 'FOLDER_MODIFY_DENIED',
  FOLDER_READ_DENIED: 'FOLDER_READ_DENIED',
  FILE_MODIFY_DENIED: 'FILE_MODIFY_DENIED',
  FILE_READ_DENIED: 'FILE_READ_DENIED',
  CANT_MOVE_TO_CHILD_FOLDER: 'CANT_MOVE_TO_CHILD_FOLDER',
  CANT_DOWNLOAD_THIS_FOLDER: 'CANT_DOWNLOAD_THIS_FOLDER',
  SHARE_URL_NEED_AUTHENTICATE: 'SHARE_URL_NEED_AUTHENTICATE',
};

/**
 * @readonly
 * @enum {string}
 */
export const TrackEventError = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
};
